/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Result = { 'ok' : RunRecordView } |
  { 'err' : RunRecordError };
export type Result_1 = { 'ok' : null } |
  { 'err' : RunRecordError };
export type Result_2 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type RunId = string;
export type RunRecordError = { 'alreadyExists' : RunId } |
  { 'invalidInput' : string } |
  { 'notAuthenticated' : null } |
  { 'notFound' : RunId };
export interface RunRecordView {
  'inputHash' : string,
  'calculatorVersion' : string,
  'outputsJson' : string,
  'createdAt' : Timestamp,
  'propertyId' : string,
  'inputProvenanceJson' : string,
  'runId' : RunId,
  'effectiveInputsJson' : string,
}
export interface SaveRunRecordInput {
  'inputHash' : string,
  'calculatorVersion' : string,
  'outputsJson' : string,
  'propertyId' : string,
  'inputProvenanceJson' : string,
  'runId' : RunId,
  'effectiveInputsJson' : string,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_2>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Delete one of the caller's run records by id.
   */
  'deleteRunRecord' : ActorMethod<[RunId], Result_1>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Static Markdown description of this canister's public API, authored from
   * / the current backend source. Reads no state.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch one of the caller's run records by id.
   */
  'getRunRecord' : ActorMethod<[RunId], [] | [RunRecordView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the caller's saved run records, newest first.
   */
  'listRunRecords' : ActorMethod<[], Array<RunRecordView>>,
  /**
   * / Save a snapshot run record for the signed-in caller.
   */
  'saveRunRecord' : ActorMethod<[SaveRunRecordInput], Result>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];