/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RunId = IDL.Text;
export const RunRecordError = IDL.Variant({
  'alreadyExists' : RunId,
  'invalidInput' : IDL.Text,
  'notAuthenticated' : IDL.Null,
  'notFound' : RunId,
});
export const Result_1 = IDL.Variant({
  'ok' : IDL.Null,
  'err' : RunRecordError,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Timestamp = IDL.Int;
export const RunRecordView = IDL.Record({
  'inputHash' : IDL.Text,
  'calculatorVersion' : IDL.Text,
  'outputsJson' : IDL.Text,
  'createdAt' : Timestamp,
  'propertyId' : IDL.Text,
  'inputProvenanceJson' : IDL.Text,
  'runId' : RunId,
  'effectiveInputsJson' : IDL.Text,
});
export const SaveRunRecordInput = IDL.Record({
  'inputHash' : IDL.Text,
  'calculatorVersion' : IDL.Text,
  'outputsJson' : IDL.Text,
  'propertyId' : IDL.Text,
  'inputProvenanceJson' : IDL.Text,
  'runId' : RunId,
  'effectiveInputsJson' : IDL.Text,
});
export const Result = IDL.Variant({
  'ok' : RunRecordView,
  'err' : RunRecordError,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteRunRecord' : IDL.Func([RunId], [Result_1], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRunRecord' : IDL.Func([RunId], [IDL.Opt(RunRecordView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listRunRecords' : IDL.Func([], [IDL.Vec(RunRecordView)], ['query']),
  'saveRunRecord' : IDL.Func([SaveRunRecordInput], [Result], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RunId = IDL.Text;
  const RunRecordError = IDL.Variant({
    'alreadyExists' : RunId,
    'invalidInput' : IDL.Text,
    'notAuthenticated' : IDL.Null,
    'notFound' : RunId,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : RunRecordError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Timestamp = IDL.Int;
  const RunRecordView = IDL.Record({
    'inputHash' : IDL.Text,
    'calculatorVersion' : IDL.Text,
    'outputsJson' : IDL.Text,
    'createdAt' : Timestamp,
    'propertyId' : IDL.Text,
    'inputProvenanceJson' : IDL.Text,
    'runId' : RunId,
    'effectiveInputsJson' : IDL.Text,
  });
  const SaveRunRecordInput = IDL.Record({
    'inputHash' : IDL.Text,
    'calculatorVersion' : IDL.Text,
    'outputsJson' : IDL.Text,
    'propertyId' : IDL.Text,
    'inputProvenanceJson' : IDL.Text,
    'runId' : RunId,
    'effectiveInputsJson' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : RunRecordView, 'err' : RunRecordError });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteRunRecord' : IDL.Func([RunId], [Result_1], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRunRecord' : IDL.Func([RunId], [IDL.Opt(RunRecordView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listRunRecords' : IDL.Func([], [IDL.Vec(RunRecordView)], ['query']),
    'saveRunRecord' : IDL.Func([SaveRunRecordInput], [Result], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };